# syntax=docker/dockerfile:1
# check=skip=all
# above is crucial fix for latest docker 20251123
# build has to be 'docker build --check -t cic -f ./dockerfile-cic .'

# couldn't get telnet onto python image, but can do with ubuntu
# ubuntu 24.04 brings all kinds of pain around pip
FROM ubuntu:22.04
RUN apt-get update && apt-get install build-essential cmake telnet -y
RUN apt-get install python3 python3-dev python3-pip python3-setuptools -y
RUN pip install pexpect sshkeyboard flask-restx flask-cors

ADD cic /cic
ADD pyproject.toml /pyproject.toml
ADD data /data
ADD msc /msc

ENV PYTHONPATH="${PYTHONPATH}:/cic"

CMD ["python3", "cic/app.py"]
