# couldn't get telnet onto python image, but can do with ubuntu
# ubuntu 24.04 brings all kinds of pain around pip
FROM ubuntu:22.04
RUN apt-get update && apt-get install build-essential cmake telnet -y
RUN apt-get install python3 python3-dev python3-pip python3-setuptools -y
RUN pip install pexpect sshkeyboard flask-restx

ADD cic /cic
ADD pyproject.toml /pyproject.toml
ADD data /data
ADD docker /docker
RUN #pip install .

ENV PYTHONPATH="${PYTHONPATH}:/cic"
ENV AM_I_IN_A_DOCKER_CONTAINER=Yes

CMD ["python3", "cic/app.py"]
